--delete from ITEM_2_5_test where YEAR(ext_CreatedDate)<2015
--select * into  ITEM_2_5_test from EXT_ITEM
--select * from HISTORY_MASTER_2_6_test
--drop table ITEM_2_5_test
--insert into HISTORY_MASTER_2_6_test select * from EXT_HISTORY_MASTER where YEAR(ext_PostingDate)=2015